alter table ATTACHMENTS drop constraint FK_ATTACHMENTS_PRODUCT_MODEL;
alter table ATTACHMENTS DROP CONSTRAINT ATTACHMENTS_PKEY;
alter table ATTACHMENTS rename column PRODUCT_MODEL_ID to ID;
ALTER TABLE ATTACHMENTS ADD CONSTRAINT ATTACHMENTS_PKEY PRIMARY KEY (ID);
alter table ATTACHMENTS add column PRODUCT_MODEL_ID varchar(255);
alter table ATTACHMENTS add column IS_PREVIEW_IMAGE boolean;
alter table ATTACHMENTS add constraint FK_ATTACHMENTS_PRODUCT_MODEL foreign key (PRODUCT_MODEL_ID) references PRODUCT_MODEL(ID);